version: "3.9"
services:
#  db:
#    image: postgres:15
#    container_name: github_parser_db
#    restart: always
#    ports:
#      - 5432:5432
#    env_file:
#      - .env
#      - .env-non-dev
##    volumes:
##      - db_data:/var/lib/postgresql/data
#
  redis:
    image: redis:7
    container_name: github_parser_redis
    ports:
      - 6379:6379
    restart: always
    env_file:
      - .env
      - .env-non-dev
#    volumes:
#      - redis_data:/app/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_parser_server
    command: sh -c "python -m gunicorn github_parser.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8080"
    ports:
      - 7354:8080
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
#      - db
      - redis
#    volumes:
#      - server_data:/app/data

#volumes:
#  db_data:
#  redis_data:
#  server_data: