version: "3.9"
services:
  redis:
    image: redis:7
    container_name: github_api_app_redis
    ports:
      - 6379:6379
    restart: always
    env_file:
      - .env
      - .env-non-dev
    volumes:
      - redis_data:/app/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_api_app_server
    ports:
      - 7354:8080
    restart: always
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - redis
    volumes:
      - server_data:/app/data

volumes:
  redis_data:
  server_data: